project:
  type: website
  output-dir: docs

website:
  title: "Xuecheng Gao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Resume Xuecheng Gao.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



